sudo: false

language: elixir
elixir:
  - 1.5
env:
  - MIX_ENV=test
install:
  - mix do local.hex --force, local.rebar --force
  - mix do deps.get, compile, ecto.create, ecto.migrate
  - nvm install stable
  - nvm use stable
script:
  - mix test
